version: "3.11"
services:
  database:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    container_name: notes-app-DB
    networks:
      - notes-app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - db=Notes
      - db_port=27017
    container_name: notes-app-backend
    networks:
      - notes-app-network

networks:
  notes-app-network:
    driver: bridge
